import QtQuick
import Quickshell
import qs.Services

Item {
    id: root

    property var pluginService: null
    property string trigger: ":"

    signal itemsChanged()

    property var emojiDatabase: [
        {emoji: "😀", name: "Grinning Face", keywords: ["happy", "smile", "grin"]},
        {emoji: "😃", name: "Grinning Face with Big Eyes", keywords: ["happy", "joy", "smile"]},
        {emoji: "😄", name: "Grinning Face with Smiling Eyes", keywords: ["happy", "joy", "laugh"]},
        {emoji: "😁", name: "Beaming Face with Smiling Eyes", keywords: ["happy", "grin", "excited"]},
        {emoji: "😆", name: "Grinning Squinting Face", keywords: ["laugh", "happy", "excited"]},
        {emoji: "😅", name: "Grinning Face with Sweat", keywords: ["hot", "happy", "laugh", "relief"]},
        {emoji: "🤣", name: "Rolling on the Floor Laughing", keywords: ["lol", "laugh", "rofl"]},
        {emoji: "😂", name: "Face with Tears of Joy", keywords: ["laugh", "cry", "joy"]},
        {emoji: "🙂", name: "Slightly Smiling Face", keywords: ["smile", "happy"]},
        {emoji: "🙃", name: "Upside-Down Face", keywords: ["silly", "sarcasm"]},
        {emoji: "😉", name: "Winking Face", keywords: ["wink", "flirt"]},
        {emoji: "😊", name: "Smiling Face with Smiling Eyes", keywords: ["happy", "blush", "smile"]},
        {emoji: "😇", name: "Smiling Face with Halo", keywords: ["angel", "innocent"]},
        {emoji: "🥰", name: "Smiling Face with Hearts", keywords: ["love", "crush", "hearts"]},
        {emoji: "😍", name: "Smiling Face with Heart-Eyes", keywords: ["love", "crush", "hearts"]},
        {emoji: "🤩", name: "Star-Struck", keywords: ["eyes", "excited", "star"]},
        {emoji: "😘", name: "Face Blowing a Kiss", keywords: ["kiss", "love"]},
        {emoji: "😗", name: "Kissing Face", keywords: ["kiss", "love"]},
        {emoji: "😚", name: "Kissing Face with Closed Eyes", keywords: ["kiss", "love"]},
        {emoji: "😙", name: "Kissing Face with Smiling Eyes", keywords: ["kiss", "love"]},
        {emoji: "😋", name: "Face Savoring Food", keywords: ["yum", "delicious", "food"]},
        {emoji: "😛", name: "Face with Tongue", keywords: ["tongue", "silly"]},
        {emoji: "😜", name: "Winking Face with Tongue", keywords: ["wink", "tongue", "silly"]},
        {emoji: "🤪", name: "Zany Face", keywords: ["crazy", "wild", "silly"]},
        {emoji: "😝", name: "Squinting Face with Tongue", keywords: ["tongue", "silly"]},
        {emoji: "🤑", name: "Money-Mouth Face", keywords: ["money", "rich", "cash"]},
        {emoji: "🤗", name: "Hugging Face", keywords: ["hug", "love"]},
        {emoji: "🤭", name: "Face with Hand Over Mouth", keywords: ["quiet", "oops", "secret"]},
        {emoji: "🤫", name: "Shushing Face", keywords: ["quiet", "shh", "secret"]},
        {emoji: "🤔", name: "Thinking Face", keywords: ["think", "hmm", "consider"]},
        {emoji: "🤐", name: "Zipper-Mouth Face", keywords: ["quiet", "secret", "sealed"]},
        {emoji: "🤨", name: "Face with Raised Eyebrow", keywords: ["suspicious", "skeptical"]},
        {emoji: "😐", name: "Neutral Face", keywords: ["neutral", "meh"]},
        {emoji: "😑", name: "Expressionless Face", keywords: ["blank", "meh"]},
        {emoji: "😶", name: "Face Without Mouth", keywords: ["silent", "quiet"]},
        {emoji: "😏", name: "Smirking Face", keywords: ["smirk", "sly"]},
        {emoji: "😒", name: "Unamused Face", keywords: ["annoyed", "meh"]},
        {emoji: "🙄", name: "Face with Rolling Eyes", keywords: ["annoyed", "eye roll"]},
        {emoji: "😬", name: "Grimacing Face", keywords: ["awkward", "nervous"]},
        {emoji: "😔", name: "Pensive Face", keywords: ["sad", "thoughtful"]},
        {emoji: "😪", name: "Sleepy Face", keywords: ["tired", "sleep"]},
        {emoji: "🤤", name: "Drooling Face", keywords: ["drool", "sleep"]},
        {emoji: "😴", name: "Sleeping Face", keywords: ["sleep", "tired", "zzz"]},
        {emoji: "😷", name: "Face with Medical Mask", keywords: ["sick", "mask", "doctor"]},
        {emoji: "🤒", name: "Face with Thermometer", keywords: ["sick", "ill", "fever"]},
        {emoji: "🤕", name: "Face with Head-Bandage", keywords: ["hurt", "injured", "bandage"]},
        {emoji: "🤢", name: "Nauseated Face", keywords: ["sick", "gross"]},
        {emoji: "🤮", name: "Face Vomiting", keywords: ["sick", "vomit", "puke"]},
        {emoji: "🤧", name: "Sneezing Face", keywords: ["sick", "sneeze"]},
        {emoji: "🥵", name: "Hot Face", keywords: ["hot", "sweat"]},
        {emoji: "🥶", name: "Cold Face", keywords: ["cold", "freeze"]},
        {emoji: "😵", name: "Dizzy Face", keywords: ["dizzy", "confused"]},
        {emoji: "🤯", name: "Exploding Head", keywords: ["mind blown", "shocked"]},
        {emoji: "🤠", name: "Cowboy Hat Face", keywords: ["cowboy", "hat"]},
        {emoji: "🥳", name: "Partying Face", keywords: ["party", "celebrate"]},
        {emoji: "😎", name: "Smiling Face with Sunglasses", keywords: ["cool", "sunglasses"]},
        {emoji: "🤓", name: "Nerd Face", keywords: ["nerd", "geek", "glasses"]},
        {emoji: "🧐", name: "Face with Monocle", keywords: ["fancy", "classy"]},
        {emoji: "😕", name: "Confused Face", keywords: ["confused", "puzzled"]},
        {emoji: "😟", name: "Worried Face", keywords: ["worried", "concerned"]},
        {emoji: "🙁", name: "Slightly Frowning Face", keywords: ["sad", "frown"]},
        {emoji: "☹️", name: "Frowning Face", keywords: ["sad", "frown"]},
        {emoji: "😮", name: "Face with Open Mouth", keywords: ["wow", "surprised"]},
        {emoji: "😯", name: "Hushed Face", keywords: ["surprised", "quiet"]},
        {emoji: "😲", name: "Astonished Face", keywords: ["shocked", "surprised"]},
        {emoji: "😳", name: "Flushed Face", keywords: ["blush", "embarrassed"]},
        {emoji: "🥺", name: "Pleading Face", keywords: ["puppy eyes", "please"]},
        {emoji: "😦", name: "Frowning Face with Open Mouth", keywords: ["shocked", "sad"]},
        {emoji: "😧", name: "Anguished Face", keywords: ["scared", "worried"]},
        {emoji: "😨", name: "Fearful Face", keywords: ["scared", "afraid"]},
        {emoji: "😰", name: "Anxious Face with Sweat", keywords: ["nervous", "worried"]},
        {emoji: "😥", name: "Sad but Relieved Face", keywords: ["sad", "relief"]},
        {emoji: "😢", name: "Crying Face", keywords: ["cry", "sad", "tears"]},
        {emoji: "😭", name: "Loudly Crying Face", keywords: ["cry", "sob", "sad"]},
        {emoji: "😱", name: "Face Screaming in Fear", keywords: ["scream", "scared"]},
        {emoji: "😖", name: "Confounded Face", keywords: ["confused", "frustrated"]},
        {emoji: "😣", name: "Persevering Face", keywords: ["struggle", "effort"]},
        {emoji: "😞", name: "Disappointed Face", keywords: ["sad", "disappointed"]},
        {emoji: "😓", name: "Downcast Face with Sweat", keywords: ["sad", "sweat"]},
        {emoji: "😩", name: "Weary Face", keywords: ["tired", "exhausted"]},
        {emoji: "😫", name: "Tired Face", keywords: ["tired", "exhausted"]},
        {emoji: "🥱", name: "Yawning Face", keywords: ["tired", "bored", "yawn"]},
        {emoji: "😤", name: "Face with Steam From Nose", keywords: ["angry", "frustrated"]},
        {emoji: "😡", name: "Pouting Face", keywords: ["angry", "mad"]},
        {emoji: "😠", name: "Angry Face", keywords: ["angry", "mad"]},
        {emoji: "🤬", name: "Face with Symbols on Mouth", keywords: ["swear", "angry", "cursing"]},
        {emoji: "❤️", name: "Red Heart", keywords: ["love", "heart", "red"]},
        {emoji: "🧡", name: "Orange Heart", keywords: ["love", "heart", "orange"]},
        {emoji: "💛", name: "Yellow Heart", keywords: ["love", "heart", "yellow"]},
        {emoji: "💚", name: "Green Heart", keywords: ["love", "heart", "green"]},
        {emoji: "💙", name: "Blue Heart", keywords: ["love", "heart", "blue"]},
        {emoji: "💜", name: "Purple Heart", keywords: ["love", "heart", "purple"]},
        {emoji: "🖤", name: "Black Heart", keywords: ["love", "heart", "black"]},
        {emoji: "🤍", name: "White Heart", keywords: ["love", "heart", "white"]},
        {emoji: "🤎", name: "Brown Heart", keywords: ["love", "heart", "brown"]},
        {emoji: "💔", name: "Broken Heart", keywords: ["heartbreak", "sad", "broken"]},
        {emoji: "❤️‍🔥", name: "Heart on Fire", keywords: ["love", "passion", "fire"]},
        {emoji: "💕", name: "Two Hearts", keywords: ["love", "hearts"]},
        {emoji: "💞", name: "Revolving Hearts", keywords: ["love", "hearts"]},
        {emoji: "💓", name: "Beating Heart", keywords: ["love", "heartbeat"]},
        {emoji: "💗", name: "Growing Heart", keywords: ["love", "hearts"]},
        {emoji: "💖", name: "Sparkling Heart", keywords: ["love", "sparkle"]},
        {emoji: "💘", name: "Heart with Arrow", keywords: ["love", "cupid"]},
        {emoji: "💝", name: "Heart with Ribbon", keywords: ["love", "gift"]},
        {emoji: "👍", name: "Thumbs Up", keywords: ["yes", "ok", "good", "agree"]},
        {emoji: "👎", name: "Thumbs Down", keywords: ["no", "bad", "disagree"]},
        {emoji: "👊", name: "Oncoming Fist", keywords: ["fist", "punch"]},
        {emoji: "✊", name: "Raised Fist", keywords: ["fist", "power"]},
        {emoji: "🤛", name: "Left-Facing Fist", keywords: ["fist", "punch"]},
        {emoji: "🤜", name: "Right-Facing Fist", keywords: ["fist", "punch"]},
        {emoji: "🤞", name: "Crossed Fingers", keywords: ["luck", "hope", "fingers crossed"]},
        {emoji: "✌️", name: "Victory Hand", keywords: ["peace", "victory"]},
        {emoji: "🤟", name: "Love-You Gesture", keywords: ["love", "hand"]},
        {emoji: "🤘", name: "Sign of the Horns", keywords: ["rock", "metal"]},
        {emoji: "👌", name: "OK Hand", keywords: ["ok", "okay", "good"]},
        {emoji: "🤌", name: "Pinched Fingers", keywords: ["italian", "fingers"]},
        {emoji: "🤏", name: "Pinching Hand", keywords: ["small", "tiny"]},
        {emoji: "👈", name: "Backhand Index Pointing Left", keywords: ["left", "point"]},
        {emoji: "👉", name: "Backhand Index Pointing Right", keywords: ["right", "point"]},
        {emoji: "👆", name: "Backhand Index Pointing Up", keywords: ["up", "point"]},
        {emoji: "👇", name: "Backhand Index Pointing Down", keywords: ["down", "point"]},
        {emoji: "☝️", name: "Index Pointing Up", keywords: ["up", "one", "point"]},
        {emoji: "✋", name: "Raised Hand", keywords: ["hand", "stop", "high five"]},
        {emoji: "🤚", name: "Raised Back of Hand", keywords: ["hand", "stop"]},
        {emoji: "🔥", name: "Fire", keywords: ["fire", "hot", "flame"]},
        {emoji: "💯", name: "Hundred Points", keywords: ["100", "perfect", "score"]},
        {emoji: "⭐", name: "Star", keywords: ["star", "favorite"]},
        {emoji: "✨", name: "Sparkles", keywords: ["sparkle", "shine", "glitter"]},
        {emoji: "💫", name: "Dizzy", keywords: ["dizzy", "stars"]},
        {emoji: "🎉", name: "Party Popper", keywords: ["party", "celebrate", "confetti"]},
        {emoji: "🎊", name: "Confetti Ball", keywords: ["party", "celebrate", "confetti"]},
        {emoji: "🎈", name: "Balloon", keywords: ["party", "balloon"]},
        {emoji: "🎁", name: "Wrapped Gift", keywords: ["gift", "present"]},
        {emoji: "🏆", name: "Trophy", keywords: ["trophy", "win", "award"]},
        {emoji: "🥇", name: "1st Place Medal", keywords: ["gold", "first", "medal", "winner"]},
        {emoji: "🥈", name: "2nd Place Medal", keywords: ["silver", "second", "medal"]},
        {emoji: "🥉", name: "3rd Place Medal", keywords: ["bronze", "third", "medal"]},
        {emoji: "⚡", name: "High Voltage", keywords: ["lightning", "bolt", "electric", "energy"]},
        {emoji: "💻", name: "Laptop", keywords: ["computer", "laptop", "pc"]},
        {emoji: "⌨️", name: "Keyboard", keywords: ["keyboard", "typing"]},
        {emoji: "🖱️", name: "Computer Mouse", keywords: ["mouse", "computer"]},
        {emoji: "🖥️", name: "Desktop Computer", keywords: ["computer", "desktop", "monitor"]},
        {emoji: "📱", name: "Mobile Phone", keywords: ["phone", "mobile", "smartphone"]},
        {emoji: "☎️", name: "Telephone", keywords: ["phone", "call"]},
        {emoji: "📞", name: "Telephone Receiver", keywords: ["phone", "call"]},
        {emoji: "✅", name: "Check Mark Button", keywords: ["check", "done", "yes", "complete"]},
        {emoji: "❌", name: "Cross Mark", keywords: ["x", "no", "wrong", "cancel"]},
        {emoji: "⚠️", name: "Warning", keywords: ["warning", "caution", "alert"]},
        {emoji: "❗", name: "Exclamation Mark", keywords: ["exclamation", "important", "alert"]},
        {emoji: "❓", name: "Question Mark", keywords: ["question", "help"]},
        {emoji: "💡", name: "Light Bulb", keywords: ["idea", "light", "bulb", "innovation"]},
        {emoji: "🔍", name: "Magnifying Glass Tilted Left", keywords: ["search", "find", "zoom"]},
        {emoji: "🔎", name: "Magnifying Glass Tilted Right", keywords: ["search", "find", "zoom"]},
        {emoji: "📝", name: "Memo", keywords: ["note", "write", "document", "text"]},
        {emoji: "📋", name: "Clipboard", keywords: ["clipboard", "copy", "paste"]},
        {emoji: "📌", name: "Pushpin", keywords: ["pin", "important"]},
        {emoji: "📍", name: "Round Pushpin", keywords: ["pin", "location"]},
        {emoji: "🚀", name: "Rocket", keywords: ["rocket", "space", "launch"]},
        {emoji: "🎯", name: "Direct Hit", keywords: ["target", "bullseye", "goal"]},
        {emoji: "⏰", name: "Alarm Clock", keywords: ["alarm", "clock", "time"]},
        {emoji: "⏱️", name: "Stopwatch", keywords: ["stopwatch", "timer"]},
        {emoji: "⏲️", name: "Timer Clock", keywords: ["timer", "clock"]},
        {emoji: "🔔", name: "Bell", keywords: ["bell", "notification", "alert"]},
        {emoji: "🔕", name: "Bell with Slash", keywords: ["mute", "silent", "no notification"]},
        {emoji: "🎵", name: "Musical Note", keywords: ["music", "note"]},
        {emoji: "🎶", name: "Musical Notes", keywords: ["music", "notes", "song"]},
        {emoji: "📷", name: "Camera", keywords: ["camera", "photo", "picture"]},
        {emoji: "📸", name: "Camera with Flash", keywords: ["camera", "photo", "flash"]},
        {emoji: "🎬", name: "Clapper Board", keywords: ["movie", "film", "action"]},
        {emoji: "🎮", name: "Video Game", keywords: ["game", "gaming", "controller"]},
        {emoji: "🎲", name: "Game Die", keywords: ["dice", "game", "random"]},
        {emoji: "🃏", name: "Joker", keywords: ["card", "joker", "playing card"]},
        {emoji: "🎨", name: "Artist Palette", keywords: ["art", "paint", "color"]},
        {emoji: "🖌️", name: "Paintbrush", keywords: ["brush", "paint", "art"]},
        {emoji: "✏️", name: "Pencil", keywords: ["pencil", "write", "draw"]},
        {emoji: "📚", name: "Books", keywords: ["books", "library", "read"]},
        {emoji: "📖", name: "Open Book", keywords: ["book", "read"]},
        {emoji: "🔖", name: "Bookmark", keywords: ["bookmark", "save"]},
        {emoji: "🌟", name: "Glowing Star", keywords: ["star", "favorite", "glow"]},
        {emoji: "💎", name: "Gem Stone", keywords: ["gem", "diamond", "jewel"]},
        {emoji: "👑", name: "Crown", keywords: ["crown", "king", "queen", "royal"]},
        {emoji: "🎓", name: "Graduation Cap", keywords: ["graduation", "education", "school"]},
        {emoji: "🏅", name: "Sports Medal", keywords: ["medal", "sports", "award"]},
        {emoji: "🎖️", name: "Military Medal", keywords: ["medal", "military", "honor"]},
        {emoji: "🌈", name: "Rainbow", keywords: ["rainbow", "colors", "pride"]},
        {emoji: "☀️", name: "Sun", keywords: ["sun", "sunny", "bright"]},
        {emoji: "🌙", name: "Crescent Moon", keywords: ["moon", "night"]},
        {emoji: "⭐", name: "Star", keywords: ["star", "favorite"]},
        {emoji: "💥", name: "Collision", keywords: ["boom", "explosion", "impact"]},
        {emoji: "💦", name: "Sweat Droplets", keywords: ["water", "sweat", "drops"]},
        {emoji: "💨", name: "Dashing Away", keywords: ["fast", "wind", "dash"]},
        {emoji: "🍕", name: "Pizza", keywords: ["pizza", "food"]},
        {emoji: "🍔", name: "Hamburger", keywords: ["burger", "food"]},
        {emoji: "🍟", name: "French Fries", keywords: ["fries", "food"]},
        {emoji: "🌮", name: "Taco", keywords: ["taco", "food"]},
        {emoji: "🌯", name: "Burrito", keywords: ["burrito", "food"]},
        {emoji: "🍿", name: "Popcorn", keywords: ["popcorn", "movie", "food"]},
        {emoji: "☕", name: "Hot Beverage", keywords: ["coffee", "tea", "hot"]},
        {emoji: "🍺", name: "Beer Mug", keywords: ["beer", "drink", "alcohol"]},
        {emoji: "🍻", name: "Clinking Beer Mugs", keywords: ["beer", "cheers", "toast"]},
        {emoji: "🍷", name: "Wine Glass", keywords: ["wine", "drink", "alcohol"]},
        {emoji: "🥂", name: "Clinking Glasses", keywords: ["champagne", "toast", "celebrate"]},
        {emoji: "🍰", name: "Shortcake", keywords: ["cake", "dessert", "birthday"]},
        {emoji: "🎂", name: "Birthday Cake", keywords: ["cake", "birthday", "celebrate"]},
        {emoji: "🍪", name: "Cookie", keywords: ["cookie", "dessert"]},
        {emoji: "🍩", name: "Doughnut", keywords: ["donut", "dessert"]},
        {emoji: "🍦", name: "Soft Ice Cream", keywords: ["ice cream", "dessert"]},
        {emoji: "🍨", name: "Ice Cream", keywords: ["ice cream", "dessert"]},
        {emoji: "🧊", name: "Ice", keywords: ["ice", "cold", "cube"]},
        {emoji: "🥤", name: "Cup with Straw", keywords: ["drink", "soda", "cup"]},
        {emoji: "🐶", name: "Dog Face", keywords: ["dog", "puppy", "pet"]},
        {emoji: "🐱", name: "Cat Face", keywords: ["cat", "kitten", "pet"]},
        {emoji: "🐭", name: "Mouse Face", keywords: ["mouse", "pet"]},
        {emoji: "🐹", name: "Hamster", keywords: ["hamster", "pet"]},
        {emoji: "🐰", name: "Rabbit Face", keywords: ["rabbit", "bunny", "pet"]},
        {emoji: "🦊", name: "Fox", keywords: ["fox", "animal"]},
        {emoji: "🐻", name: "Bear", keywords: ["bear", "animal"]},
        {emoji: "🐼", name: "Panda", keywords: ["panda", "bear", "animal"]},
        {emoji: "🐨", name: "Koala", keywords: ["koala", "animal"]},
        {emoji: "🐯", name: "Tiger Face", keywords: ["tiger", "animal"]},
        {emoji: "🦁", name: "Lion", keywords: ["lion", "animal"]},
        {emoji: "🐮", name: "Cow Face", keywords: ["cow", "animal"]},
        {emoji: "🐷", name: "Pig Face", keywords: ["pig", "animal"]},
        {emoji: "🐸", name: "Frog", keywords: ["frog", "animal"]},
        {emoji: "🐵", name: "Monkey Face", keywords: ["monkey", "animal"]},
        {emoji: "🙈", name: "See-No-Evil Monkey", keywords: ["monkey", "hide", "see no evil"]},
        {emoji: "🙉", name: "Hear-No-Evil Monkey", keywords: ["monkey", "hear no evil"]},
        {emoji: "🙊", name: "Speak-No-Evil Monkey", keywords: ["monkey", "speak no evil"]},
        {emoji: "🐔", name: "Chicken", keywords: ["chicken", "bird"]},
        {emoji: "🐧", name: "Penguin", keywords: ["penguin", "bird"]},
        {emoji: "🐦", name: "Bird", keywords: ["bird"]},
        {emoji: "🦆", name: "Duck", keywords: ["duck", "bird"]},
        {emoji: "🦅", name: "Eagle", keywords: ["eagle", "bird"]},
        {emoji: "🦉", name: "Owl", keywords: ["owl", "bird", "wise"]},
        {emoji: "🦇", name: "Bat", keywords: ["bat", "animal", "vampire"]},
        {emoji: "🐺", name: "Wolf", keywords: ["wolf", "animal"]},
        {emoji: "🐗", name: "Boar", keywords: ["boar", "pig", "animal"]},
        {emoji: "🐴", name: "Horse Face", keywords: ["horse", "animal"]},
        {emoji: "🦄", name: "Unicorn", keywords: ["unicorn", "fantasy", "magic"]},
        {emoji: "🐝", name: "Honeybee", keywords: ["bee", "insect"]},
        {emoji: "🐛", name: "Bug", keywords: ["bug", "insect"]},
        {emoji: "🦋", name: "Butterfly", keywords: ["butterfly", "insect"]},
        {emoji: "🐌", name: "Snail", keywords: ["snail", "slow"]},
        {emoji: "🐞", name: "Lady Beetle", keywords: ["ladybug", "insect"]},
        {emoji: "🐜", name: "Ant", keywords: ["ant", "insect"]},
        {emoji: "🕷️", name: "Spider", keywords: ["spider", "insect"]},
        {emoji: "🕸️", name: "Spider Web", keywords: ["web", "spider"]},
        {emoji: "🐢", name: "Turtle", keywords: ["turtle", "slow"]},
        {emoji: "🐍", name: "Snake", keywords: ["snake", "animal"]},
        {emoji: "🦎", name: "Lizard", keywords: ["lizard", "reptile"]},
        {emoji: "🦖", name: "T-Rex", keywords: ["dinosaur", "t-rex", "extinct"]},
        {emoji: "🦕", name: "Sauropod", keywords: ["dinosaur", "extinct"]},
        {emoji: "🐙", name: "Octopus", keywords: ["octopus", "sea"]},
        {emoji: "🦑", name: "Squid", keywords: ["squid", "sea"]},
        {emoji: "🦐", name: "Shrimp", keywords: ["shrimp", "seafood"]},
        {emoji: "🦞", name: "Lobster", keywords: ["lobster", "seafood"]},
        {emoji: "🦀", name: "Crab", keywords: ["crab", "seafood"]},
        {emoji: "🐡", name: "Blowfish", keywords: ["fish", "blowfish"]},
        {emoji: "🐠", name: "Tropical Fish", keywords: ["fish", "tropical"]},
        {emoji: "🐟", name: "Fish", keywords: ["fish"]},
        {emoji: "🐬", name: "Dolphin", keywords: ["dolphin", "sea"]},
        {emoji: "🐳", name: "Spouting Whale", keywords: ["whale", "sea"]},
        {emoji: "🐋", name: "Whale", keywords: ["whale", "sea"]},
        {emoji: "🦈", name: "Shark", keywords: ["shark", "sea"]},
        {emoji: "🌸", name: "Cherry Blossom", keywords: ["flower", "spring", "pink"]},
        {emoji: "💐", name: "Bouquet", keywords: ["flowers", "bouquet"]},
        {emoji: "🌹", name: "Rose", keywords: ["rose", "flower", "love"]},
        {emoji: "🥀", name: "Wilted Flower", keywords: ["flower", "wilted", "dead"]},
        {emoji: "🌺", name: "Hibiscus", keywords: ["flower", "tropical"]},
        {emoji: "🌻", name: "Sunflower", keywords: ["flower", "sunflower"]},
        {emoji: "🌼", name: "Blossom", keywords: ["flower", "blossom"]},
        {emoji: "🌷", name: "Tulip", keywords: ["flower", "tulip"]},
        {emoji: "🌱", name: "Seedling", keywords: ["plant", "seedling", "grow"]},
        {emoji: "🌲", name: "Evergreen Tree", keywords: ["tree", "pine", "forest"]},
        {emoji: "🌳", name: "Deciduous Tree", keywords: ["tree", "forest"]},
        {emoji: "🌴", name: "Palm Tree", keywords: ["tree", "palm", "tropical"]},
        {emoji: "🌵", name: "Cactus", keywords: ["cactus", "desert"]},
        {emoji: "🌾", name: "Sheaf of Rice", keywords: ["rice", "grain"]},
        {emoji: "🌿", name: "Herb", keywords: ["herb", "plant", "green"]},
        {emoji: "☘️", name: "Shamrock", keywords: ["shamrock", "clover", "lucky"]},
        {emoji: "🍀", name: "Four Leaf Clover", keywords: ["clover", "lucky", "four leaf"]},
        {emoji: "��", name: "Maple Leaf", keywords: ["leaf", "maple", "fall"]},
        {emoji: "🍂", name: "Fallen Leaf", keywords: ["leaf", "fall", "autumn"]},
        {emoji: "🍃", name: "Leaf Fluttering in Wind", keywords: ["leaf", "wind"]}
    ]

    property var unicodeCharacters: [
        {char: "©", name: "Copyright Sign", keywords: ["copyright", "legal"]},
        {char: "®", name: "Registered Sign", keywords: ["registered", "trademark", "legal"]},
        {char: "™", name: "Trade Mark Sign", keywords: ["trademark", "tm", "legal"]},
        {char: "°", name: "Degree Sign", keywords: ["degree", "temperature"]},
        {char: "±", name: "Plus-Minus Sign", keywords: ["plus minus", "math"]},
        {char: "×", name: "Multiplication Sign", keywords: ["multiply", "times", "math"]},
        {char: "÷", name: "Division Sign", keywords: ["divide", "math"]},
        {char: "≠", name: "Not Equal To", keywords: ["not equal", "math"]},
        {char: "≈", name: "Almost Equal To", keywords: ["approximately", "about", "math"]},
        {char: "≤", name: "Less Than or Equal To", keywords: ["less than equal", "math"]},
        {char: "≥", name: "Greater Than or Equal To", keywords: ["greater than equal", "math"]},
        {char: "∞", name: "Infinity", keywords: ["infinity", "infinite", "math"]},
        {char: "∑", name: "N-Ary Summation", keywords: ["sum", "sigma", "math"]},
        {char: "√", name: "Square Root", keywords: ["square root", "radical", "math"]},
        {char: "∫", name: "Integral", keywords: ["integral", "calculus", "math"]},
        {char: "∂", name: "Partial Differential", keywords: ["partial", "derivative", "math"]},
        {char: "∆", name: "Increment", keywords: ["delta", "change", "math"]},
        {char: "π", name: "Greek Small Letter Pi", keywords: ["pi", "math", "greek"]},
        {char: "α", name: "Greek Small Letter Alpha", keywords: ["alpha", "greek"]},
        {char: "β", name: "Greek Small Letter Beta", keywords: ["beta", "greek"]},
        {char: "γ", name: "Greek Small Letter Gamma", keywords: ["gamma", "greek"]},
        {char: "δ", name: "Greek Small Letter Delta", keywords: ["delta", "greek"]},
        {char: "ε", name: "Greek Small Letter Epsilon", keywords: ["epsilon", "greek"]},
        {char: "θ", name: "Greek Small Letter Theta", keywords: ["theta", "greek"]},
        {char: "λ", name: "Greek Small Letter Lambda", keywords: ["lambda", "greek"]},
        {char: "μ", name: "Greek Small Letter Mu", keywords: ["mu", "micro", "greek"]},
        {char: "σ", name: "Greek Small Letter Sigma", keywords: ["sigma", "greek"]},
        {char: "Ω", name: "Greek Capital Letter Omega", keywords: ["omega", "greek"]},
        {char: "←", name: "Leftwards Arrow", keywords: ["arrow", "left"]},
        {char: "→", name: "Rightwards Arrow", keywords: ["arrow", "right"]},
        {char: "↑", name: "Upwards Arrow", keywords: ["arrow", "up"]},
        {char: "↓", name: "Downwards Arrow", keywords: ["arrow", "down"]},
        {char: "↔", name: "Left Right Arrow", keywords: ["arrow", "bidirectional"]},
        {char: "⇐", name: "Leftwards Double Arrow", keywords: ["double arrow", "left"]},
        {char: "⇒", name: "Rightwards Double Arrow", keywords: ["double arrow", "right"]},
        {char: "⇔", name: "Left Right Double Arrow", keywords: ["double arrow", "bidirectional"]},
        {char: "•", name: "Bullet", keywords: ["bullet", "dot", "point"]},
        {char: "◦", name: "White Bullet", keywords: ["bullet", "dot", "point"]},
        {char: "‣", name: "Triangular Bullet", keywords: ["bullet", "triangle"]},
        {char: "⁃", name: "Hyphen Bullet", keywords: ["bullet", "dash"]},
        {char: "…", name: "Horizontal Ellipsis", keywords: ["ellipsis", "dot dot dot"]},
        {char: "–", name: "En Dash", keywords: ["dash", "hyphen"]},
        {char: "—", name: "Em Dash", keywords: ["dash", "long dash"]},
        {char: "¡", name: "Inverted Exclamation Mark", keywords: ["exclamation", "spanish"]},
        {char: "¿", name: "Inverted Question Mark", keywords: ["question", "spanish"]},
        {char: "§", name: "Section Sign", keywords: ["section", "paragraph"]},
        {char: "¶", name: "Pilcrow Sign", keywords: ["paragraph", "pilcrow"]},
        {char: "†", name: "Dagger", keywords: ["dagger", "footnote"]},
        {char: "‡", name: "Double Dagger", keywords: ["double dagger", "footnote"]},
        {char: "‰", name: "Per Mille Sign", keywords: ["per mille", "percent"]},
        {char: "€", name: "Euro Sign", keywords: ["euro", "currency", "money"]},
        {char: "£", name: "Pound Sign", keywords: ["pound", "currency", "money"]},
        {char: "¥", name: "Yen Sign", keywords: ["yen", "currency", "money"]},
        {char: "¢", name: "Cent Sign", keywords: ["cent", "currency", "money"]},
        {char: "₹", name: "Indian Rupee Sign", keywords: ["rupee", "currency", "money"]},
        {char: "₽", name: "Ruble Sign", keywords: ["ruble", "currency", "money"]},
        {char: "₩", name: "Won Sign", keywords: ["won", "currency", "money"]},
        {char: "¤", name: "Currency Sign", keywords: ["currency", "money"]},
        {char: "★", name: "Black Star", keywords: ["star", "favorite"]},
        {char: "☆", name: "White Star", keywords: ["star", "favorite"]},
        {char: "♠", name: "Black Spade Suit", keywords: ["spade", "card", "suit"]},
        {char: "♣", name: "Black Club Suit", keywords: ["club", "card", "suit"]},
        {char: "♥", name: "Black Heart Suit", keywords: ["heart", "card", "suit"]},
        {char: "♦", name: "Black Diamond Suit", keywords: ["diamond", "card", "suit"]},
        {char: "♪", name: "Eighth Note", keywords: ["music", "note"]},
        {char: "♫", name: "Beamed Eighth Notes", keywords: ["music", "notes"]},
        {char: "♬", name: "Beamed Sixteenth Notes", keywords: ["music", "notes"]},
        {char: "♭", name: "Music Flat Sign", keywords: ["flat", "music"]},
        {char: "♮", name: "Music Natural Sign", keywords: ["natural", "music"]},
        {char: "♯", name: "Music Sharp Sign", keywords: ["sharp", "music"]},
        {char: "✓", name: "Check Mark", keywords: ["check", "tick", "yes"]},
        {char: "✗", name: "Ballot X", keywords: ["x", "cross", "no"]},
        {char: "✘", name: "Heavy Ballot X", keywords: ["x", "cross", "no"]},
        {char: "☐", name: "Ballot Box", keywords: ["checkbox", "box"]},
        {char: "☑", name: "Ballot Box with Check", keywords: ["checkbox", "checked"]},
        {char: "☒", name: "Ballot Box with X", keywords: ["checkbox", "unchecked"]},
        {char: "⚠", name: "Warning Sign", keywords: ["warning", "caution"]},
        {char: "☢", name: "Radioactive Sign", keywords: ["radioactive", "hazard"]},
        {char: "☣", name: "Biohazard Sign", keywords: ["biohazard", "hazard"]},
        {char: "⚡", name: "High Voltage Sign", keywords: ["lightning", "electric", "voltage"]},
        {char: "☀", name: "Black Sun with Rays", keywords: ["sun", "sunny"]},
        {char: "☁", name: "Cloud", keywords: ["cloud", "weather"]},
        {char: "☂", name: "Umbrella", keywords: ["umbrella", "rain"]},
        {char: "☃", name: "Snowman", keywords: ["snowman", "snow", "winter"]},
        {char: "☄", name: "Comet", keywords: ["comet", "space"]},
        {char: "☎", name: "Black Telephone", keywords: ["phone", "telephone"]},
        {char: "☏", name: "White Telephone", keywords: ["phone", "telephone"]},
        {char: "✉", name: "Envelope", keywords: ["email", "mail", "letter"]},
        {char: "✏", name: "Pencil", keywords: ["pencil", "write"]},
        {char: "✂", name: "Black Scissors", keywords: ["scissors", "cut"]},
        {char: "♻", name: "Black Universal Recycling Symbol", keywords: ["recycle", "recycling"]},
        {char: "♿", name: "Wheelchair Symbol", keywords: ["wheelchair", "accessibility"]},
        {char: "⚕", name: "Staff of Aesculapius", keywords: ["medical", "medicine"]},
        {char: "☮", name: "Peace Symbol", keywords: ["peace"]},
        {char: "☯", name: "Yin Yang", keywords: ["yin yang", "balance"]},
        {char: "☸", name: "Wheel of Dharma", keywords: ["dharma", "buddhism"]},
        {char: "✝", name: "Latin Cross", keywords: ["cross", "christianity"]},
        {char: "☪", name: "Star and Crescent", keywords: ["islam", "crescent"]},
        {char: "✡", name: "Star of David", keywords: ["star of david", "judaism"]},
        {char: "☦", name: "Orthodox Cross", keywords: ["cross", "orthodox"]},
        {char: "♂", name: "Male Sign", keywords: ["male", "gender"]},
        {char: "♀", name: "Female Sign", keywords: ["female", "gender"]},
        {char: "⚧", name: "Transgender Symbol", keywords: ["transgender", "gender"]},
        {char: "⚲", name: "Neuter", keywords: ["neuter", "gender"]},
        {char: "⚥", name: "Male and Female Sign", keywords: ["hermaphrodite", "gender"]},
        {char: "☠", name: "Skull and Crossbones", keywords: ["skull", "death", "danger"]},
        {char: "⚰", name: "Coffin", keywords: ["coffin", "death"]},
        {char: "⚱", name: "Funeral Urn", keywords: ["urn", "death"]},
        {char: "♨", name: "Hot Springs", keywords: ["hot springs", "onsen"]},
        {char: "🝔", name: "Alchemical Symbol for Air", keywords: ["air", "alchemy"]},
        {char: "🜂", name: "Alchemical Symbol for Fire", keywords: ["fire", "alchemy"]},
        {char: "🜄", name: "Alchemical Symbol for Water", keywords: ["water", "alchemy"]},
        {char: "🜃", name: "Alchemical Symbol for Earth", keywords: ["earth", "alchemy"]}
    ]

    Component.onCompleted: {
        if (pluginService) {
            trigger = pluginService.loadPluginData("emojiLauncher", "trigger", ":")
        }
    }

    function getItems(query) {
        const items = []
        const lowerQuery = query ? query.toLowerCase() : ""

        for (let i = 0; i < emojiDatabase.length; i++) {
            const emoji = emojiDatabase[i]
            if (!query ||
                emoji.name.toLowerCase().includes(lowerQuery) ||
                emoji.emoji.includes(query) ||
                emoji.keywords.some(k => k.includes(lowerQuery))) {
                items.push({
                    name: emoji.emoji + "  " + emoji.name,
                    icon: "smiley",
                    comment: emoji.keywords.join(", "),
                    action: "copy:" + emoji.emoji,
                    categories: ["Emoji & Unicode Launcher"]
                })
            }
        }

        for (let i = 0; i < unicodeCharacters.length; i++) {
            const unicode = unicodeCharacters[i]
            if (!query ||
                unicode.name.toLowerCase().includes(lowerQuery) ||
                unicode.char.includes(query) ||
                unicode.keywords.some(k => k.includes(lowerQuery))) {
                items.push({
                    name: unicode.char + "  " + unicode.name,
                    icon: "translate",
                    comment: unicode.keywords.join(", "),
                    action: "copy:" + unicode.char,
                    categories: ["Emoji & Unicode Launcher"]
                })
            }
        }

        return items.slice(0, 50)
    }

    function executeItem(item) {
        if (!item || !item.action) {
            console.warn("EmojiLauncher: Invalid item or action")
            return
        }

        const actionParts = item.action.split(":")
        const actionType = actionParts[0]
        const actionData = actionParts.slice(1).join(":")

        if (actionType === "copy") {
            Quickshell.execDetached(["sh", "-c", "echo -n '" + actionData + "' | wl-copy"])
            if (typeof ToastService !== "undefined") {
                ToastService.showInfo("Copied " + actionData + " to clipboard")
            }
        }
    }

    onTriggerChanged: {
        if (pluginService) {
            pluginService.savePluginData("emojiLauncher", "trigger", trigger)
        }
        itemsChanged()
    }
}
