# general block from hyprland.conf - dude from dotfiles

general {
  gaps_in = 4
  gaps_out = 10

  border_size = 2

  col.active_border = rgba(b8f00cee) rgba(3ee17cff) 45deg
  col.inactive_border = rgb(229,101,101)

  # Enable resizing windows by dragging borders/gaps
  resize_on_border = false

  # Enable at your own risk, see wiki for tearing info
  allow_tearing = false

  # dwindle is default, if you want your main app on the left and all others to be smooched to the right, do master
  layout = dwindle
} 
