# input related source folder - random dotfile guy


# https://wiki.hypr.land/Configuring/Variables/#input
input {
  kb_layout = de
  kb_variant = 
  kb_model = 
  kb_options = caps:escape # i use nvim btw
  kb_rules = 
  follow_mouse = 1
  sensitivity = -0.8
  accel_profile = adaptive
} 

# https://wiki.hypr.land/Configuring/Variables/#gestures
gestures {
  workspace_swipe_forever = true
} 

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
  name = znt0001:00-14e5:650e-touchpad # my touchpad name dont mind this
  sensitivity = 0
  disable_while_typing = true
  middle_button_emulation = true
  enabled = true
}
