# Miscellaneous block from hyprland.conf - dude from dotfiles

misc {
  force_default_wallpaper = 0 # Set to 0 or 1 to disable anime mascot wallpapers
  disable_hyprland_logo = true # Disable random Hyprland logo / anime girl background
}
