# source file for all variables - dude from the dotfiles

# -------------------------------------------------------------------
# just some program variables for a lil modularity cause i like that
# -------------------------------------------------------------------

$terminal = kitty
$fileManager = nautilus
$menu = fuzzel
$browser = qutebrowser
$screenshot = flameshot gui
$emoji_picker = hypremoji
$lock = hyprlock
$calculator = Scripts/fuzzel-calculator.py

# website shortcut variables
$youtube = qutebrowser youtube.com
$chatgpt = qutebrowser chatgpt.com
$modrinth = qutebrowser modrinth.com

# custom script-variables
$notes = ~/Scripts/notes.sh
$clipboard_dmenu = $scripts/fuzzel-clipboard.sh
$theme_switcher = $scripts/theme-switcher.sh
$music = fish -c $scripts/fuzzel-music.sh
$fuzzel = fish -c $scrips/fuzzel-scripts.sh
$minimization = $scripts/fuzzel-minimize.sh
$choose_bar = $scripts/choose-bar.sh

$timers = $scripts/timers.sh
