# window rules from hyprland.conf - dude from dotfiles

# Refer to:
# - Window rules: https://wiki.hypr.land/Configuring/Window-Rules/
# - Workspace rules: https://wiki.hypr.land/Configuring/Workspace-Rules/

# ----------------------
# Suppress maximize requests from apps
# Useful to prevent apps from automatically maximizing
windowrule = suppressevent maximize, class:.*

# ----------------------
# Fix dragging issues with XWayland apps
windowrule = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0

# ----------------------
# make network manager GUI float
windowrulev2 = float, title:^(.*Network Manager.*)$

# HyprEmoji config
source = ~/.config/hypremoji/hypremoji.conf
bind = SUPER, I, Exec, hyprsettings # automatically added not me
