#########################
# Hyprland config file ##
#########################

################
### MONITORS ###
################

monitor = eDP-1,1920x1080@144,0x0,1

#########################
### PROGRAM VARIABLES ###
#########################

# variable for the source path
$source = ~/.config/hypr/sources

source = $source/variables.conf

#################
### AUTOSTART ###
#################

# source file for autostarting stuff
source = $source/autostart.conf

#####################################
###   ENVIRONMENT VARIABLES    ######
#####################################

# Sourcing file for cursor theme
source = ~/.config/hypr/sources/cursor.conf

###################
### PERMISSIONS ###
###################

# Changes require a Hyprland restart and are not applied on-the-fly for security reasons

source = $source/permissions.conf

#####################
### LOOK AND FEEL ###
#####################

# Refer to https://wiki.hypr.land/Configuring/Variables/

# ----------------------
# General Settings
# ----------------------

source = $source/general.conf

# ----------------------
# Window Decoration
# ----------------------
 
source = $source/window-decorations.conf

# ----------------------
# Animations
# ----------------------

# dont mess with this, exept if you dont want any animations, probably not a good idea to change the values tho

source = $source/animations.conf

###############################
# hyprpm plugin configuration #
###############################

source = $source/plugins.conf

# ----------------------------
# Workspace Rules / Smart Gaps
# ----------------------------

source = $source/workspace-rulesNsmart-gaps.conf

# ----------------------
# Miscellaneous
# ----------------------

source = $source/miscellaneous.conf

#############
### INPUT ###
#############

source = $source/input.conf

# -----------------
# KEYBINDINGS     |
# -----------------

source = $source/keybindings.conf

##################################
###   WINDOWS AND WORKSPACES   ###
##################################

source = $source/window-rules.conf
